/**
 * Issue Formatter Service - Formats feedback data into GitHub issue markdown
 *
 * Supports two modes:
 * 1. Raw format: Simple structured markdown with all data
 * 2. AI-refined format: Uses Claude API to generate better titles, summaries
 */

import { CapturedError } from '../store/slice';

// ============================================================================
// TYPES
// ============================================================================

export interface FeedbackData {
  error?: CapturedError;
  userDescription: string;
  systemInfo: {
    pluginVersion: string;
    obsidianVersion: string;
    platform: string;
    platformVersion: string;
  };
  consoleLogs?: string;
  storeState?: string;
  navigationHistory?: string[];
}

export interface RefinedIssue {
  title: string;
  body: string;
}

// ============================================================================
// ISSUE FORMATTER SERVICE
// ============================================================================

class IssueFormatterService {
  /**
   * Format feedback data as raw markdown
   */
  formatRaw(data: FeedbackData): string {
    const sections: string[] = [];

    // Header
    sections.push('## Bug Report\n');

    // Error info
    if (data.error) {
      sections.push(`**Error:** ${data.error.message}\n`);
    }

    // User description
    sections.push('**User Description:**');
    sections.push(data.userDescription || '_No description provided_');
    sections.push('');

    // Environment
    sections.push('**Environment:**');
    sections.push(`- InterBrain Version: ${data.systemInfo.pluginVersion}`);
    sections.push(`- Obsidian Version: ${data.systemInfo.obsidianVersion}`);
    sections.push(`- Platform: ${data.systemInfo.platform}`);
    sections.push('');

    // Stack trace
    if (data.error?.stack) {
      sections.push('**Stack Trace:**');
      sections.push('```');
      sections.push(data.error.stack);
      sections.push('```');
      sections.push('');
    }

    // Console logs
    if (data.consoleLogs) {
      sections.push('<details>');
      sections.push('<summary>Console Logs (last 50)</summary>');
      sections.push('');
      sections.push('```');
      sections.push(data.consoleLogs);
      sections.push('```');
      sections.push('</details>');
      sections.push('');
    }

    // Store state
    if (data.storeState) {
      sections.push('<details>');
      sections.push('<summary>Store State Snapshot</summary>');
      sections.push('');
      sections.push('```json');
      sections.push(data.storeState);
      sections.push('```');
      sections.push('</details>');
      sections.push('');
    }

    // Navigation history
    if (data.navigationHistory && data.navigationHistory.length > 0) {
      sections.push('**Navigation History:**');
      sections.push(data.navigationHistory.map((id) => `- ${id}`).join('\n'));
      sections.push('');
    }

    // Footer
    sections.push('---');
    sections.push('_Auto-generated by InterBrain Feedback System_');

    return sections.join('\n');
  }

  /**
   * Format feedback data with AI refinement
   *
   * Uses Claude API to:
   * - Generate a concise, descriptive title
   * - Summarize the issue
   * - Infer reproduction steps
   * - Suggest investigation areas
   */
  async formatWithAi(data: FeedbackData): Promise<RefinedIssue> {
    // Try to use Claude API if available
    try {
      const refined = await this.callClaudeApi(data);
      if (refined) {
        return refined;
      }
    } catch (err) {
      console.warn('[IssueFormatter] AI refinement failed, using raw format:', err);
    }

    // Fallback to raw format
    return {
      title: this.generateSimpleTitle(data),
      body: this.formatRaw(data),
    };
  }

  /**
   * Generate a simple title from the error/description
   */
  private generateSimpleTitle(data: FeedbackData): string {
    if (data.error) {
      const errorLine = data.error.message.split('\n')[0].slice(0, 60);
      return `Bug: ${errorLine}`;
    }

    const descLine = data.userDescription.split('\n')[0].slice(0, 60);
    return `Bug: ${descLine}`;
  }

  /**
   * Call Claude API for issue refinement
   */
  private async callClaudeApi(data: FeedbackData): Promise<RefinedIssue | null> {
    // Import settings service to check for API key
    const { settingsStatusService } = await import(
      '../../settings/settings-status-service'
    );

    const apiKey = settingsStatusService.getSettings()?.claudeApiKey;
    if (!apiKey) {
      return null; // No API key, can't use AI
    }

    const prompt = this.buildPrompt(data);

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307',
        max_tokens: 1500,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Claude API error: ${response.status}`);
    }

    const result = await response.json();
    const content = result.content?.[0]?.text;

    if (!content) {
      return null;
    }

    // Parse the structured response
    return this.parseAiResponse(content, data);
  }

  /**
   * Build the prompt for Claude
   */
  private buildPrompt(data: FeedbackData): string {
    return `You are analyzing a bug report for InterBrain, an Obsidian plugin for knowledge gardening.

Please analyze this bug report and provide:
1. A concise title (max 60 chars)
2. A 1-2 sentence summary
3. Category: Bug / UX Issue / Performance / Crash
4. Estimated complexity: Trivial / Minor / Moderate / Complex
5. Inferred reproduction steps (if possible)
6. Suggested investigation areas

Error: ${data.error?.message || 'No error message'}
Stack trace: ${data.error?.stack?.slice(0, 500) || 'None'}
User description: ${data.userDescription}
Platform: ${data.systemInfo.platform}
Plugin version: ${data.systemInfo.pluginVersion}

Respond in this exact format:
TITLE: [your title]
SUMMARY: [your summary]
CATEGORY: [category]
COMPLEXITY: [complexity]
STEPS:
1. [step]
2. [step]
INVESTIGATION:
- [area to investigate]
- [area to investigate]`;
  }

  /**
   * Parse Claude's response into structured format
   */
  private parseAiResponse(content: string, data: FeedbackData): RefinedIssue {
    // Extract fields from response
    const titleMatch = content.match(/TITLE:\s*(.+)/);
    const summaryMatch = content.match(/SUMMARY:\s*(.+)/);
    const categoryMatch = content.match(/CATEGORY:\s*(.+)/);
    const complexityMatch = content.match(/COMPLEXITY:\s*(.+)/);
    const stepsMatch = content.match(/STEPS:\n([\s\S]*?)(?=INVESTIGATION:|$)/);
    const investigationMatch = content.match(/INVESTIGATION:\n([\s\S]*?)$/);

    const title = titleMatch?.[1]?.trim() || this.generateSimpleTitle(data);
    const summary = summaryMatch?.[1]?.trim() || data.userDescription;
    const category = categoryMatch?.[1]?.trim() || 'Bug';
    const complexity = complexityMatch?.[1]?.trim() || 'Unknown';
    const steps = stepsMatch?.[1]?.trim() || 'Unable to determine';
    const investigation = investigationMatch?.[1]?.trim() || 'General debugging';

    // Build refined body
    const sections: string[] = [];

    sections.push(`## Bug Report: ${title}\n`);
    sections.push(`**Summary:** ${summary}\n`);
    sections.push(`**Category:** ${category}\n`);
    sections.push(`**Estimated Complexity:** ${complexity}\n`);

    sections.push('**Reproduction Steps:**');
    sections.push(steps);
    sections.push('');

    if (data.error) {
      sections.push('**Expected vs Actual:**');
      sections.push('- Expected: Normal operation');
      sections.push(`- Actual: ${data.error.message}`);
      sections.push('');
    }

    sections.push('**Suggested Investigation:**');
    sections.push(investigation);
    sections.push('');

    // Raw data in collapsible
    sections.push('<details>');
    sections.push('<summary>Raw Data</summary>');
    sections.push('');
    sections.push(this.formatRaw(data));
    sections.push('</details>');
    sections.push('');

    sections.push('---');
    sections.push('_AI-refined by InterBrain Feedback System_');

    return {
      title: `Bug: ${title}`,
      body: sections.join('\n'),
    };
  }
}

// ============================================================================
// SINGLETON EXPORT
// ============================================================================

export const issueFormatterService = new IssueFormatterService();
