name: Bug Report
description: Report a bug to help us improve the InterBrain Obsidian plugin
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug! 🐛

        Please fill out the details below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open Obsidian
        2. Activate InterBrain plugin
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What went wrong?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - "macOS (Apple Silicon - M1/M2/M3/M4)"
        - "macOS (Intel)"
        - "Windows"
        - "Linux"
        - "Other"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Your operating system version
      placeholder: "e.g., macOS 14.1, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: Your Obsidian version (Help → About)
      placeholder: "e.g., v1.4.16"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: InterBrain Plugin Version
      description: InterBrain plugin version (check in Community Plugins)
      placeholder: "e.g., v0.6.0"
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs or Screenshots
      description: |
        Any error messages from Obsidian's Developer Console (Cmd+Opt+I on Mac, Ctrl+Shift+I on others) or helpful screenshots
      placeholder: Paste error messages or drag and drop screenshots here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help (other plugins installed, vault size, etc.)
      placeholder: Any other details that might be relevant...