name: Epic
description: High-level vision for major feature areas
title: "Epic: [Major Feature Area]"
labels: ["epic"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Template
        Use this template to create high-level vision issues for major feature areas.
        
  - type: input
    id: epic-name
    attributes:
      label: Epic Name
      description: Name of the major feature area
      placeholder: e.g., "Plugin Infrastructure", "3D Spatial Visualization"
    validations:
      required: true
      
  - type: textarea
    id: vision
    attributes:
      label: Vision
      description: High-level description of the major feature area and its role in InterBrain's overall vision
      placeholder: Describe the high-level vision for this epic...
    validations:
      required: true
      
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: Major outcomes that define success for this epic
      placeholder: |
        - [ ] Major outcome 1
        - [ ] Major outcome 2
        - [ ] Major outcome 3
    validations:
      required: true
      
  - type: textarea
    id: related-epics
    attributes:
      label: Related Epics
      description: Links to other epics this depends on or enables
      placeholder: Links to related epic issues...
      
  - type: textarea
    id: child-specifications
    attributes:
      label: Child Specifications
      description: List of specifications that will implement this epic
      placeholder: |
        - [ ] Specification 1
        - [ ] Specification 2
        - [ ] Specification 3
    validations:
      required: true
      
  - type: textarea
    id: development-notes
    attributes:
      label: Development Notes
      description: Notes about development approach, dependencies, or implementation considerations
      placeholder: |
        - Dependencies on other epics
        - Technical considerations
        - Implementation approach notes